# Generated by Django 2.2.4 on 2019-11-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshopping', '0002_auto_20191102_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.SmallIntegerField(default=0),
        ),
    ]
