# Generated by Django 2.2.4 on 2019-11-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshopping', '0003_auto_20191102_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.SmallIntegerField(default=''),
        ),
    ]
