# Generated by Django 2.2.4 on 2019-11-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshopping', '0004_auto_20191104_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.SmallIntegerField(default=100),
        ),
    ]
