# Generated by Django 2.2.4 on 2019-11-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshopping', '0005_auto_20191104_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.SmallIntegerField(),
        ),
    ]
