# Generated by Django 2.2.4 on 2019-11-04 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshopping', '0009_auto_20191104_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_category',
        ),
    ]
