# Generated by Django 2.2.4 on 2019-11-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshopping', '0011_product_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.BigIntegerField(),
        ),
    ]
