# Generated by Django 2.2.4 on 2019-11-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshopping', '0024_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('Register_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=12)),
                ('phone', models.CharField(default='', max_length=10)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
